'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace DriveWorksSpecificationAutomation
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="CreateSpecificationResult", [Namespace]:="http://schemas.datacontract.org/2004/07/DriveWorks.Applications.Autopilot.Connect"& _ 
        "ors.Http"),  _
     System.SerializableAttribute()>  _
    Partial Public Class CreateSpecificationResult
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SpecificationNameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private StatusField As DriveWorksSpecificationAutomation.SpecificationRequestResult
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property SpecificationName() As String
            Get
                Return Me.SpecificationNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SpecificationNameField, value) <> true) Then
                    Me.SpecificationNameField = value
                    Me.RaisePropertyChanged("SpecificationName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Status() As DriveWorksSpecificationAutomation.SpecificationRequestResult
            Get
                Return Me.StatusField
            End Get
            Set
                If (Me.StatusField.Equals(value) <> true) Then
                    Me.StatusField = value
                    Me.RaisePropertyChanged("Status")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="SpecificationRequestResult", [Namespace]:="http://schemas.datacontract.org/2004/07/DriveWorks.Applications.Autopilot.Connect"& _ 
        "ors")>  _
    Public Enum SpecificationRequestResult As Integer
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        NotAvailable = 0
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        FailedNoReason = 1
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        FailedInvalidTransitionNameOrTransitionDisabledByConditions = 2
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        FailedInvalidSpecificationName = 3
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        FailedInvalidProjectName = 4
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Succeeded = 5
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        SucceededWithInputWarnings = 6
    End Enum
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="", ConfigurationName:="DriveWorksSpecificationAutomation.IHttpConnectorService", SessionMode:=System.ServiceModel.SessionMode.NotAllowed)>  _
    Public Interface IHttpConnectorService
        
        <System.ServiceModel.OperationContractAttribute(Action:="urn:IHttpConnectorService/CreateSpecification", ReplyAction:="urn:IHttpConnectorService/CreateSpecificationResponse")>  _
        Function CreateSpecification(ByVal projectName As String, ByVal transitionName As String, ByVal values As System.Collections.Generic.Dictionary(Of String, String)) As DriveWorksSpecificationAutomation.CreateSpecificationResult
        
        <System.ServiceModel.OperationContractAttribute(Action:="urn:IHttpConnectorService/CreateSpecification", ReplyAction:="urn:IHttpConnectorService/CreateSpecificationResponse")>  _
        Function CreateSpecificationAsync(ByVal projectName As String, ByVal transitionName As String, ByVal values As System.Collections.Generic.Dictionary(Of String, String)) As System.Threading.Tasks.Task(Of DriveWorksSpecificationAutomation.CreateSpecificationResult)
        
        <System.ServiceModel.OperationContractAttribute(Action:="urn:IHttpConnectorService/EditSpecification", ReplyAction:="urn:IHttpConnectorService/EditSpecificationResponse")>  _
        Function EditSpecification(ByVal projectName As String, ByVal transitionName As String, ByVal specificationName As String, ByVal specificationId As String, ByVal operationName As String, ByVal values As System.Collections.Generic.Dictionary(Of String, String)) As DriveWorksSpecificationAutomation.CreateSpecificationResult
        
        <System.ServiceModel.OperationContractAttribute(Action:="urn:IHttpConnectorService/EditSpecification", ReplyAction:="urn:IHttpConnectorService/EditSpecificationResponse")>  _
        Function EditSpecificationAsync(ByVal projectName As String, ByVal transitionName As String, ByVal specificationName As String, ByVal specificationId As String, ByVal operationName As String, ByVal values As System.Collections.Generic.Dictionary(Of String, String)) As System.Threading.Tasks.Task(Of DriveWorksSpecificationAutomation.CreateSpecificationResult)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IHttpConnectorServiceChannel
        Inherits DriveWorksSpecificationAutomation.IHttpConnectorService, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class HttpConnectorServiceClient
        Inherits System.ServiceModel.ClientBase(Of DriveWorksSpecificationAutomation.IHttpConnectorService)
        Implements DriveWorksSpecificationAutomation.IHttpConnectorService
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function CreateSpecification(ByVal projectName As String, ByVal transitionName As String, ByVal values As System.Collections.Generic.Dictionary(Of String, String)) As DriveWorksSpecificationAutomation.CreateSpecificationResult Implements DriveWorksSpecificationAutomation.IHttpConnectorService.CreateSpecification
            Return MyBase.Channel.CreateSpecification(projectName, transitionName, values)
        End Function
        
        Public Function CreateSpecificationAsync(ByVal projectName As String, ByVal transitionName As String, ByVal values As System.Collections.Generic.Dictionary(Of String, String)) As System.Threading.Tasks.Task(Of DriveWorksSpecificationAutomation.CreateSpecificationResult) Implements DriveWorksSpecificationAutomation.IHttpConnectorService.CreateSpecificationAsync
            Return MyBase.Channel.CreateSpecificationAsync(projectName, transitionName, values)
        End Function
        
        Public Function EditSpecification(ByVal projectName As String, ByVal transitionName As String, ByVal specificationName As String, ByVal specificationId As String, ByVal operationName As String, ByVal values As System.Collections.Generic.Dictionary(Of String, String)) As DriveWorksSpecificationAutomation.CreateSpecificationResult Implements DriveWorksSpecificationAutomation.IHttpConnectorService.EditSpecification
            Return MyBase.Channel.EditSpecification(projectName, transitionName, specificationName, specificationId, operationName, values)
        End Function
        
        Public Function EditSpecificationAsync(ByVal projectName As String, ByVal transitionName As String, ByVal specificationName As String, ByVal specificationId As String, ByVal operationName As String, ByVal values As System.Collections.Generic.Dictionary(Of String, String)) As System.Threading.Tasks.Task(Of DriveWorksSpecificationAutomation.CreateSpecificationResult) Implements DriveWorksSpecificationAutomation.IHttpConnectorService.EditSpecificationAsync
            Return MyBase.Channel.EditSpecificationAsync(projectName, transitionName, specificationName, specificationId, operationName, values)
        End Function
    End Class
End Namespace
